### ISSUE TITLE
Unable to start normally

### ISSUE THREAD

**Issue by WhiteCloud0123** [papow65/rustaclysm#1]
Put on the necessary folder, and then after the preparation, execute "cargo run", and the following error is displayed.

![T8IO %30%SC~K(K`RTR_1X3](https://user-images.githubusercontent.com/112397151/221405819-c345f49a-5e47-4400-8a9b-b215ec4d9343.png)

This is the structure in the assets folder
![G(D}5WYQ61}M8P9@76IUA 6](https://user-images.githubusercontent.com/112397151/221406122-4910eb47-fcf9-468e-8209-756f9ac6f931.png)

And the necessary “UltimateCataclysm” exists in the gfx folder.
![RJE)Q`F$}AVJFY}2(1D`%JL](https://user-images.githubusercontent.com/112397151/221406068-3f1b3ffe-a4b1-4ae2-83f9-cb5d99754b07.png)

**Comment by papow65** [comment]
@WhiteCloud0123, does the file `assets/data/json/monsters/zed-classic.json` exist on your system?

**Comment by WhiteCloud0123** [comment]
I checked it carefully and found the file exists. @papow65

**Comment by WhiteCloud0123** [comment]
I asked another friend to test it. This problem also occurred.

**Comment by papow65** [comment]
@WhiteCloud0123, can you please confirm that this issue is fixed by fa29941?

**Comment by WhiteCloud0123** [comment]
> @WhiteCloud0123, can you please confirm that this issue is fixed by [fa29941](https://github.com/papow65/rustaclysm/commit/fa299418f6b2933f04e267e6db40001e5948c1b1)?

![picture_1](https://user-images.githubusercontent.com/112397151/223014280-fc5ebb48-d102-4434-aa2e-25d1583f52bc.png)

it fixed.
